version: '3.9'

services:
  web:
    build: .
    command: gunicorn credit_approval.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A credit_approval worker --loglevel=info
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:

