# Generated by Django 5.2.4 on 2025-08-04 08:10

import django.db.models.deletion
from django.db import migrations, models

# This migration creates the initial Loan model with fields for loan details.
# It includes fields for loan ID, loan amount, tenure, interest rate, monthly installment,
# EMIs paid on time, start date, end date, and a foreign key relationship to the Customer model.
# The loan ID is set as the primary key.
# This migration is the first one for the loans app, establishing the basic structure for loan data storage.

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.FloatField()),
                ('tenure', models.IntegerField(help_text='Loan tenure in months')),
                ('interest_rate', models.FloatField()),
                ('monthly_installment', models.FloatField()),
                ('emis_paid_on_time', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
